package default_package;

import java.util.Map;
import java.util.UUID;

import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.document.DeleteItemOutcome;
import com.amazonaws.services.dynamodbv2.document.DynamoDB;
import com.amazonaws.services.dynamodbv2.document.Item;
import com.amazonaws.services.dynamodbv2.document.PutItemOutcome;
import com.amazonaws.services.dynamodbv2.document.Table;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.amazonaws.services.dynamodbv2.model.ScanRequest;
import com.amazonaws.services.dynamodbv2.model.ScanResult;

public class DynamoDB_Handle_Input implements DB_Handle_Input{

	static String tableName = "";
	AmazonDynamoDB client;
	DynamoDB dynamoDB;
	Table table;
    private String orderId;


	@DynamoDBHashKey(attributeName = "orderId")
    @DynamoDBAutoGeneratedKey
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
	
	public DynamoDB_Handle_Input(String t_name){
		//create table
		//DynamoDB_Connection dbConn = new DynamoDB_Connection(t_name);
		
		tableName = t_name;
		client = AmazonDynamoDBClientBuilder.standard()
    			.withRegion(Regions.US_WEST_2)
    			.build();

       dynamoDB = new DynamoDB(client);
       table = dynamoDB.getTable(tableName);
	}
	
	@Override
	public void insertTask(TaskItem t) {
		String uniqueID = UUID.randomUUID().toString();
		// Generate the item 
		
        Item item = new Item()
           .withPrimaryKey("ID", uniqueID) 
           .withString("taskName", t.name)
           .withString("dueDate", t.date)
           .withString("priority", t.priority);
     // Add item to the table  
        PutItemOutcome outcome = table.putItem(item);
		
	}

	@Override
	public void removeItem(String taskName) {
		   
		//Table table = dynamoDB.getTable("ProductList");
	//	DeleteItemOutcome outcome = table.deleteItem("taskName", taskName);
//		System.out.println(outcome);
		
		// TODO Auto-generated method stub
		ScanRequest scanRequest = new ScanRequest()
	        	.withTableName(tableName);
	    
		String removeId = "";
		String formattedName = "{S: "+taskName+",}";
		ScanResult result = client.scan(scanRequest);
		for (Map<String, AttributeValue> i : result.getItems()){
			if (formattedName.equals((i.get("taskName"))+"")){
				removeId = (""+ i.get("ID"));
				System.out.println(removeId);
			} else {
				System.out.println(i.get("taskName") +" != "+(formattedName));
			}
		    
		}
	}

	@Override
	public void printList() {
		printList("1");
		// TODO Auto-generated method stub
		
	}

	@Override
	public void printList(String sortedBy) {
		ScanRequest scanRequest = new ScanRequest()
	        	.withTableName(tableName);
	        
		ScanResult result = client.scan(scanRequest);
		for (Map<String, AttributeValue> i : result.getItems()){
		    System.out.println(i);
		}
		// TODO Auto-generated method stub
		
	}

}
